In [1]:
from fm4ar.utils.hdf import save_to_hdf
import pandas as pd
from tqdm import tqdm
import numpy as np
import h5py

In [2]:
df = pd.read_pickle('FM_dataset.pkl')

In [4]:
# df['theta'] = [f for f in tqdm(df[['zenith', 'azimuth']].values)]
df['theta'] = df['zenith'].values
df['theta']

0          2.287569
1          2.081253
2          2.738480
3          2.252435
4          2.033719
             ...   
3113105    2.505863
3113106    3.051014
3113107    2.532559
3113108    2.554265
3113109    1.621370
Name: theta, Length: 3113110, dtype: float64

In [10]:
# data = {'theta': np.array([vec.flatten() for vec in df['theta'].values]),
#         'flux': np.array([vec.flatten() for vec in df['latent_vec'].values])}
data = {'theta': np.array([vec.flatten() for vec in df['theta'].values]),
         'flux': np.array([vec.flatten() for vec in df['latent_vec'].values])}

In [11]:
data

{'theta': array([[2.28756862],
        [2.08125283],
        [2.73847967],
        ...,
        [2.53255933],
        [2.55426486],
        [1.62137027]]),
 'flux': array([[  0.      ,   0.      ,   0.      , ...,   0.      ,   0.      ,
           0.      ],
        [  0.      ,   0.      ,   0.      , ...,   0.      ,   0.      ,
           0.      ],
        [  0.      , 114.393036,   0.      , ...,   0.      ,   0.      ,
           0.      ],
        ...,
        [  0.      ,   0.      ,   0.      , ...,   0.      ,   0.      ,
         121.59051 ],
        [  0.      ,   0.      ,   0.      , ...,   0.      ,   0.      ,
           0.      ],
        [  0.      ,   0.      ,   0.      , ...,   0.      ,   0.      ,
           0.      ]], dtype=float32)}

In [12]:
save_to_hdf('./FM_dataset_zenith.hdf', **data)

In [13]:
with h5py.File('./FM_dataset_zenith.hdf', "r") as f:
    print(f.keys())  # Output: <KeysViewHDF5 ['array1', 'array2', 'array3']>
    print(f['flux'][:])  # Access the data for 'array1'
    print(f['theta'][:])  # Access the data for 'array2'


<KeysViewHDF5 ['flux', 'theta']>
[[  0.         0.         0.       ...   0.         0.         0.      ]
 [  0.         0.         0.       ...   0.         0.         0.      ]
 [  0.       114.393036   0.       ...   0.         0.         0.      ]
 ...
 [  0.         0.         0.       ...   0.         0.       121.59051 ]
 [  0.         0.         0.       ...   0.         0.         0.      ]
 [  0.         0.         0.       ...   0.         0.         0.      ]]
[[2.28756862]
 [2.08125283]
 [2.73847967]
 ...
 [2.53255933]
 [2.55426486]
 [1.62137027]]


In [ ]:
# create data with euclidean theta
zenith = df['zenith'].values
azimuth = df['azimuth'].values
x = np.sin(zenith) * np.cos(azimuth)
y = np.sin(zenith) * np.sin(azimuth)
z = np.cos(zenith)
theta = np.stack([x, y, z], axis=1)
data['theta'] = theta
save_to_hdf('./FM_dataset_eucl.hdf', **data)

In [10]:
with h5py.File('./FM_dataset_eucl.hdf', "r") as f:
    print(f.keys())  # Output: <KeysViewHDF5 ['array1', 'array2', 'array3']>
    print(f['flux'][:])  # Access the data for 'array1'
    print(f['theta'][:])  # Access the data for 'array2'

<KeysViewHDF5 ['flux', 'theta']>
[[  0.         0.         0.       ...   0.         0.         0.      ]
 [  0.         0.         0.       ...   0.         0.         0.      ]
 [  0.       114.393036   0.       ...   0.         0.         0.      ]
 ...
 [  0.         0.         0.       ...   0.         0.       121.59051 ]
 [  0.         0.         0.       ...   0.         0.         0.      ]
 [  0.         0.         0.       ...   0.         0.         0.      ]]
[[-0.3345449  -0.67564068 -0.65695463]
 [-0.28909523 -0.82323619 -0.48857561]
 [-0.20418816  0.33495328 -0.91984428]
 ...
 [ 0.48125813  0.30928993 -0.82020141]
 [-0.53144485 -0.15695843 -0.83242442]
 [-0.70672651 -0.70567847 -0.05055238]]
